[package]
name = "payjoin_flutter"
version = "0.13.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[build-dependencies]
flutter_rust_bridge_codegen = { version = "=2.0.0-dev.24"  }
anyhow = "1.0.68"
[dependencies]
payjoin_ffi = {git = "https://github.com/LtbLightning/payjoin-ffi", branch = "v0.13"}
flutter_rust_bridge = { version = "=2.0.0-dev.24"  }
serde = "1.0.89"
serde_json = "1.0.96"
anyhow = "1.0.68"
lazy_static = "1.4.0"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
