[package]
name = "payjoin_flutter"
version = "0.13.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

anyhow = "1.0.68"
[dependencies]
ohttp = { version = "0.5.1" }
payjoin_ffi = {git = "https://github.com/LtbLightning/payjoin-ffi", branch = "main"}
flutter_rust_bridge = "=2.0.0-dev.31"
anyhow = "1.0.68"
tokio = "1.36.0"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
